---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: import-zcash-snapshot-ipfs-
  labels:
    import: zcash-snapshot-ipfs
spec:
  taskRef:
    name: ipfs-pin-cid
  params:
    - name: IPFSHOST
      value: /dns/ipfs-cache/tcp/5001
    - name: CONFIGMAP_IPFS_KEY
      value: SNAPSHOT_IPFSCID
