---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: create-secret-
spec:
  serviceAccountName: tekton
  taskSpec:
    steps:
      - name: create-secret
        image: google/cloud-sdk:latest
        command:
          - /bin/bash
        args: 
          - -c
          - kubectl create secret generic monitoring-grafana-admin --from-literal=password=$(openssl rand -hex 20)