---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: create-secret-
spec:
  serviceAccountName: tekton
  taskSpec:
    steps:
      - name: create-secret
        image: google/cloud-sdk:latest
        command:
          - /bin/bash
        args: 
          - -c
          - kubectl create secret generic minio-secret-key --from-literal=ACCESSKEYID=minio --from-literal=SECRETACCESSKEY=$(openssl rand -hex 20)