---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-binaries-bucket
spec:
  serviceAccountName: tekton
  taskSpec:
    params:
      - name: MINIOHOST
        default: http://minio:9000
        type: string
      - name: MINIOBUCKET
        default: binaries
        type: string
    steps:
      - name: create-bucket
        image: minio/mc
        env:
          - name: ACCESSKEYID
            valueFrom:
              secretKeyRef:
                name: minio-secret-key
                key: ACCESSKEYID
          - name: SECRETACCESSKEY
            valueFrom:
              secretKeyRef:
                name: minio-secret-key
                key: SECRETACCESSKEY                        
        script: |
          #!/bin/sh
          set -xe -o pipefail
          mc config host add minio $(params.MINIOHOST) ${ACCESSKEYID} ${SECRETACCESSKEY}
          mc mb minio/$(params.MINIOBUCKET)/
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-cache-bucket
spec:
  serviceAccountName: tekton
  taskSpec:
    params:
      - name: MINIOHOST
        default: http://minio:9000
        type: string
      - name: MINIOBUCKET
        default: cache
        type: string
    steps:
      - name: create-bucket
        image: minio/mc
        env:
          - name: ACCESSKEYID
            valueFrom:
              secretKeyRef:
                name: minio-secret-key
                key: ACCESSKEYID
          - name: SECRETACCESSKEY
            valueFrom:
              secretKeyRef:
                name: minio-secret-key
                key: SECRETACCESSKEY                        
        script: |
          #!/bin/sh
          set -xe -o pipefail
          mc config host add minio $(params.MINIOHOST) ${ACCESSKEYID} ${SECRETACCESSKEY}
          mc mb minio/$(params.MINIOBUCKET)/          