---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: import-zcash-params-
  labels:
    import: zcash-params
spec:
  workspaces:
    - name: zcash-params
      emptyDir: {}
  taskSpec:
    workspaces:
        - name: zcash-params
          mountPath: /zcash-params  
    params:
    - name: MINIOHOST
      default: http://minio:9000
      type: string
    - name: MINIOBUCKET
      default: cache
      type: string                
    steps:
      - name: get-zcash-params
        image: electriccoinco/zcashd
        envFrom:
          - configMapRef:
              name: zcash-tnb-base
        script: |
          #!/bin/sh
          env | sort
          set -xe
          whoami
          pwd
          zcash-fetch-params
          ls -l ${HOME}/.zcash-params/
          cp -rv ${HOME}/.zcash-params/* /zcash-params
      - name: import-zcash-params
        image: rclone/rclone
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-secret-key
                key: ACCESSKEYID 
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret-key
                key: SECRETACCESSKEY                         
        script: |
          #!/bin/sh
          env | sort
          set -xe
          whoami
          pwd
          cat > rclone.config <<EOT
          [minio]
          type = s3
          provider = Minio
          env_auth = true
          region = us-east-1
          endpoint = $(params.MINIOHOST)
          location_constraint =
          server_side_encryption =
          EOT
          cat rclone.config
          rclone -vvv --config ./rclone.config copy \
            /zcash-params \
            minio:/$(params.MINIOBUCKET)/zcash-params
