---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: import-zcash-tnb-artifacts-ipfs-
  labels:
    import: zcash-tnb-artifacts-ipfs
spec:
  taskRef:
    name: ipfs-pin-cid
  params:
    - name: IPFSHOST
      value: /dns/ipfs-cache/tcp/5001
    - name: CONFIGMAP_IPFS_KEY
      value: ARTIFACTS_IPFSCID
