---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: import-zcash-tnb-bundle-
  labels:
    import: zcash-tnb-bundle
spec:
  taskSpec:
    params:
    - name: MINIOHOST
      default: http://minio:9000
      type: string                   
    steps:    
      - name: import-zcash-tnb-bundle
        image: rclone/rclone
        envFrom:
          - configMapRef:
              name: zcash-tnb-bundle
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-secret-key
                key: ACCESSKEYID 
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret-key
                key: SECRETACCESSKEY                         
        script: |
          #!/bin/sh
          env | sort
          set -xe -o pipefail
          whoami
          pwd
          cat > rclone.config <<EOT
          [minio]
          type = s3
          provider = Minio
          env_auth = true
          region = us-east-1
          endpoint = $(params.MINIOHOST)
          location_constraint =
          server_side_encryption =
          EOT
          cat rclone.config
          rclone -vvv --config ./rclone.config copyurl \
            ${ARCHIVE_HTTP_SRC} \
            minio:/binaries/${ARCHIVE_NAME}
          rclone -vvv --config ./rclone.config copyurl \
            ${SNAPSHOT_HTTP_SRC} \
            minio:/cache/${SNAPSHOT_NAME}