{
 "title": "Zcash Testnet in a box",
 "description": "Dashboard to monitor a group of zcashd instances each with a corresponding zcashd_exporter providing prometheus metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(up{job=\"zcashd_exporter\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Zcashd version",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "zcashd_info" }
   ]
  },
  {
   "title": "Wallet total balance",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, zcash_wallet_balance{type=\"private\"})",
     "legendFormat": "private"
    },
    {
     "expr": "topk(1, zcash_wallet_balance{type=\"transparent\"})",
     "legendFormat": "transparent"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 0 },
   "repeat": "pod",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_blocks{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_verification_progress{kubernetes_pod_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_blocks{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_verification_progress{kubernetes_pod_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "private balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, zcash_wallet_balance{type=\"private\"})",
     "legendFormat": "private"
    }
   ]
  },
  {
   "title": "Deprecation Height",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "targets": [
    { "expr": "zcashd_deprecation_height" }
   ]
  },
  {
   "title": "$pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_blocks{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_verification_progress{kubernetes_pod_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "transparent balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, zcash_wallet_balance{type=\"transparent\"})",
     "legendFormat": "transparent"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "repeat": "pod",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zcash_mempool_bytes{kubernetes_pod_name=\"$pod\"}",
       "legendFormat": "zcash_mempool_bytes"
      },
      {
       "expr": "zcash_mempool_size{kubernetes_pod_name=\"$pod\"}",
       "legendFormat": "zcash_mempool_size"
      }
     ]
    },
    {
     "title": "$pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zcash_mempool_bytes{kubernetes_pod_name=\"$pod\"}",
       "legendFormat": "zcash_mempool_bytes"
      },
      {
       "expr": "zcash_mempool_size{kubernetes_pod_name=\"$pod\"}",
       "legendFormat": "zcash_mempool_size"
      }
     ]
    }
   ]
  },
  { "title": "Peer traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "repeat": "pod",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zcash_peer_bytes_sent{kubernetes_pod_name=\"$pod\"}[1m])",
     "legendFormat": "{{ addr }} - {{ subver }} recv"
    },
    {
     "expr": "rate(zcash_peer_bytes_sent{kubernetes_pod_name=\"$pod\"}[1m])",
     "legendFormat": "{{ addr }} - {{ subver }} sent"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zcash_peer_bytes_sent{kubernetes_pod_name=\"$pod\"}[1m])",
     "legendFormat": "{{ addr }} - {{ subver }} recv"
    },
    {
     "expr": "rate(zcash_peer_bytes_sent{kubernetes_pod_name=\"$pod\"}[1m])",
     "legendFormat": "{{ addr }} - {{ subver }} sent"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zcash_peer_bytes_sent{kubernetes_pod_name=\"$pod\"}[1m])",
     "legendFormat": "{{ addr }} - {{ subver }} recv"
    },
    {
     "expr": "rate(zcash_peer_bytes_sent{kubernetes_pod_name=\"$pod\"}[1m])",
     "legendFormat": "{{ addr }} - {{ subver }} sent"
    }
   ]
  },
  {
   "title": "Blocks until deprecation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "repeat": "pod",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zcashd_deprecation_height{kubernetes_pod_name=\"$pod\"} - zcash_blocks{kubernetes_pod_name=\"$pod\"}"
      }
     ]
    },
    {
     "title": "$pod",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zcashd_deprecation_height{kubernetes_pod_name=\"$pod\"} - zcash_blocks{kubernetes_pod_name=\"$pod\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Number of Peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "repeat": "pod",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(zcash_peer_version{kubernetes_pod_name=\"$pod\"})"
      }
     ]
    },
    {
     "title": "$pod",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(zcash_peer_version{kubernetes_pod_name=\"$pod\"})"
      }
     ]
    },
    {
     "title": "$pod",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(zcash_peer_version{kubernetes_pod_name=\"$pod\"})"
      }
     ]
    }
   ]
  },
  { "title": "Peer info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$pod",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "zcash_peer_version{kubernetes_pod_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "zcash_peer_version{kubernetes_pod_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "zcash_peer_version{kubernetes_pod_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod height",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "repeat": "pod",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zcash_blocks{kubernetes_pod_name=\"$pod\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "$pod height",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zcash_blocks{kubernetes_pod_name=\"$pod\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "$pod height",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zcash_blocks{kubernetes_pod_name=\"$pod\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Zcash logsfiles",
     "type": "logs",
     "gridPos": { "h": 26, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "{filename=\"/home/zcash/.zcash/debug.log\"}"
      }
     ]
    }
   ]
  }
 ]
}