---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
data:
  ini: |
    [auth]
    default_home_dashboard_path = /etc/grafana/provisioning/dashboards/zcash-tnb.json
    [auth.anonymous]
    enabled = true
    [paths]
    provisioning = /etc/grafana/provisioning
    [log]
    level = debug
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  default: |
    apiVersion: 1
    providers:
    - name: 'Zcashd TNB'
      orgId: 1
      folder: ''
      folderUid: ''
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 10
      allowUiUpdates: false
      options:
        path: /etc/grafana/provisioning/dashboards/zcash-tnb.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  config: |
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    rule_files:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'zcashd_exporter'
        kubernetes_sd_configs:
          - role: pod
            selectors:
              - role: pod
                label: "app=zcash-with-exporter"
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: zcashd-exporter
          - source_labels: [__meta_kubernetes_pod_label_network]
            action: keep
            target_label: network
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  prometheus: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://localhost:9090
      version: 1
      editable: false
  loki: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://localhost:3100
      version: 1
      editable: false
      jsonData:
        maxLines: 1000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
data:
  config: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    schema_config:
      configs:
      - from: 2018-04-15
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 168h

    storage_config:
      boltdb:
        directory: /tmp/loki/index

      filesystem:
        directory: /tmp/loki/chunks
