---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-deploy
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get"]  
- apiGroups: ["*"]
  resources: ["configmaps", "deployments", "statefulsets", "secrets", "pods"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "tasks", "taskruns"]
  verbs: ["create"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-can-deploy
subjects:
- kind: ServiceAccount
  name: tekton
roleRef:
  kind: Role
  name: tekton-deploy
  apiGroup: rbac.authorization.k8s.io