---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./tekton/serviceAccount.yml
  - ./ipfs/stateful-set.yml
  - ./monitoring/configmap.yml
  - ./monitoring/service.yml
  - ./monitoring/serviceaccount.yml
  - ./monitoring/statefulset.yml
  - ./deploy/configmaps-tnb.yml
  - ./tekton/tasks/ipfs-pin-cid.yml
  - ./deploy/zcash-peers.yml
  - ./deploy/zcash-tnb-bundle-deploy.yml