---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcash-tnb-bundle
data:
  ARCHIVE_NAME: zcashd-tnb-artifacts-0dade79ce.tgz 
  ARCHIVE_HTTP_SRC: "https://gateway.pinata.cloud/ipfs/QmW5drTSwxdUizNvxQzPPd67215NM6Qp53KWmX9VNX8URQ"
  ARTIFACTS_NAME: zcashd-tnb-artifacts-0dade79ce.tgz 
  ARTIFACTS_IPFSCID: QmW5drTSwxdUizNvxQzPPd67215NM6Qp53KWmX9VNX8URQ
  ARTIFACTS_HTTP_SRC: "https://gateway.pinata.cloud/ipfs/QmW5drTSwxdUizNvxQzPPd67215NM6Qp53KWmX9VNX8URQ"
  ZCASH_PARAMS_IPFSCID: QmUSFo5zgPPXXejidzFWZcxVyF3AJH6Pr9br6Xisdww1r1
  SNAPSHOT_NAME: zcash-testnet-miner-1488649.tgz
  SNAPSHOT_IPFSCID: QmP2LueQ3t8v4jpMaWwvDsSRKuxT9bVv6osBsf3yNkw5b4
  SNAPSHOT_HTTP_SRC: "https://gateway.pinata.cloud/ipfs/QmP2LueQ3t8v4jpMaWwvDsSRKuxT9bVv6osBsf3yNkw5b4"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcashd-testnet-miner-config
data:
  ZCASHD_RPCPORT: "38232"
  ZCASHD_RPCUSER: "zcashrpc"
  ZCASHD_MINETOADDRESS: "ztestsapling1xlnh6kjnv2up7at0ume3mx8sk85g0f0v02xfyzmeq4fm9tqpkp8lwhu9qqkumfmqa79yzdrlfyf"
  WALLET_NAME: "wallet-zdrlfyf"
  zcash.conf: |
    listen=1
    testnet=1
    showmetrics=0
    logips=1
    maxtipage=10000000
    dns=0
    dnsseed=0
    gen=1
    experimentalfeatures=1
    txindex=1
    insightexplorer=0
    printtoconsole=1
    equihashsolver=tromp
    genproclimit=1
    rpcuser=zcashrpc
    rpcport=38232
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcash-tnb-base
data:
  ZCASHD_NETWORK: "testnet"
  ZCASHD_RPCUSER: "zcashrpc"
  ZCASHD_LOGIPS: "1"
  ZCASHD_EXPERIMENTALFEATURES: "1"
  ZCASHD_TXINDEX: "1"
  ZCASHD_INSIGHTEXPLORER: "1"
  ZCASHD_ZMQPORT: "9904"
  ZCASHD_RPCBIND: "0.0.0.0"
  ZCASHD_RPCPORT: "38232"
  ZCASHD_ALLOWIP: "0.0.0.0/0"
